services:
  accounts:
    image: "raveeshaward/accounts:1.0.0"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - EliteInvest
  loans:
    image: "raveeshaward/loans:1.0.0"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - EliteInvest
  cards:
    image: "raveeshaward/cards:1.0.0"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - EliteInvest
networks:
  EliteInvest:
    driver: "bridge"  #docker will create a bridge where all microservices within the network can communicate with each other
