
spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lowerCaseServiceId: true
#  cloud:
#    gateway:
#      discovery:  # asks to connect to the discovery server (eureka server) and locate all details abt the microservices
#        locator:
#          enabled: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
     access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Edger server/ Gateway Server"
    version: "1.0.0"

logging:
  level:
    com:
      springboot:
        gatewayserver: DEBUG

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000


