build:
  version: "3.0.0"

cards:
  message: "Welcome to EliteInvest Cards related local APIs"
  contactDetails:
    name: "Raveesha Weerasinghe"
    email: "raveesha.weerasinghe22@gmail.com"
  onCallSupport:
    - (555) 568-9876
    - (555) 568-9877